In [168]:
import json as js
import pandas as pd
import numpy as np
import re

In [169]:
file = open('/home/kshgrk/huen/main/out.json')

In [170]:
raw = js.loads(file.read())

In [171]:
df = pd.DataFrame.from_dict(raw, orient='columns')

In [172]:
df = df.T

In [173]:
df

,id,conversation_id,created_at,date,time,timezone,user_id,username,name,place,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1484774733694763008,1484774733694763008,2022-01-22 06:27:36 UTC,2022-01-22,06:27:36,+0000,1213270339293077504,abhinav93453817,Simon,,...,,,,,,[],,,,
1,1484774725381279747,1484774725381279747,2022-01-22 06:27:34 UTC,2022-01-22,06:27:34,+0000,1464129467677556739,phuonglequang2,Phuong Le Quang,,...,,,,,,[],,,,
2,1484774720440606723,1484771623601418244,2022-01-22 06:27:33 UTC,2022-01-22,06:27:33,+0000,3227226404,bitcoinshaykh,The Bitcoin Shaykh,,...,,,,,,"[{'screen_name': 'MoneyMetaverse', 'name': 'Mo...",,,,
3,1484774720377610241,1484769279883026436,2022-01-22 06:27:33 UTC,2022-01-22,06:27:33,+0000,1026573960,psktamer,Tamer YOÄžUN,,...,,,,,,"[{'screen_name': 'consnovvvv', 'name': 'Con Sn...",,,,
4,1484774720340135942,1484652712046247936,2022-01-22 06:27:33 UTC,2022-01-22,06:27:33,+0000,1311173387373346817,shu_tash,Tash Shu,,...,,,,,,"[{'screen_name': 'JohalMiles', 'name': 'Miles ...",,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17742,1484690803272335360,1484673941222289409,2022-01-22 00:54:06 UTC,2022-01-22,00:54:06,+0000,1550795581,iupdate,Sam Kohl,,...,,,,,,"[{'screen_name': 'briantong', 'name': 'Brian T...",,,,
17743,1484690801766584322,1484690801766584322,2022-01-22 00:54:06 UTC,2022-01-22,00:54:06,+0000,2560082425,gargiulomichael,Michael Gargiulo,,...,,,,,,[],,,,
17744,1484690796876075012,1484690796876075012,2022-01-22 00:54:04 UTC,2022-01-22,00:54:04,+0000,1359444971447795712,aawtperkdjoea,AwtPerkJoe,,...,,,,,,[],,,,
17745,1484690787892076544,1484690787892076544,2022-01-22 00:54:02 UTC,2022-01-22,00:54:02,+0000,774678899712294912,newscryptobot,DoodBot,,...,,,,,,[],,,,
done,done,done,done,done,done,done,done,done,done,done,...,done,done,done,done,done,done,done,done,done,done

In [174]:
df1 = df[['tweet', 'replies_count', 'retweets_count', 'likes_count', 'hashtags', 'cashtags', 'language']]

In [175]:
df1 = df1[df1.language == 'en']

In [176]:
df1.shape

(12029, 7)

In [177]:
df1.retweets_count = df1.retweets_count.astype(int)
df1.replies_count = df1.replies_count.astype(int)
df1.likes_count = df1.likes_count.astype(int)

In [178]:
df1.dtypes

tweet             object
replies_count      int64
retweets_count     int64
likes_count        int64
hashtags          object
cashtags          object
language          object
dtype: object

In [179]:
df1 = df1.sort_values(['likes_count'], ascending=[False])

In [180]:
from textblob import TextBlob

In [181]:
def clean_tweet(tweet):
    return ' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t]) |(\w+:\/\/\S+)", " ", tweet).split())

In [182]:
df1.tweet = df.tweet.astype('string')

In [183]:
df1.tweet = df1.tweet.apply(clean_tweet)

In [184]:
def getPolarity(text):
    return TextBlob(text).sentiment.polarity

In [185]:
df1['polarity'] = df1.tweet.apply(getPolarity)

In [186]:
df1.head(10)

,tweet,replies_count,retweets_count,likes_count,hashtags,cashtags,language,polarity
9385,My BTC in long term cold storage will not be t...,187,122,2985,[],[],en,-0.325000
8531,The waterfall,212,193,1559,[],[],en,0.000000
16138,Sharing some #Bitcoin history Avg correction d...,93,163,875,"[bitcoin, btc]",[],en,0.150000
13601,Did you buy the dip Drop me the #100xgem of to...,36,865,874,"[100xgem, hodl, btc, eth, solana, bnb, cardano...",[],en,0.000000
15763,How are your top #gems doing today Shill me.. ...,43,785,804,"[gems, metaverse, gamefi, bscgem, solanart, nf...",[],en,0.225000
11108,"On this day one year ago 1 $BTC $32,957 1 $ETH...",117,189,748,[],"[btc, eth, bnb, sol, ada, luna, avax, matic, c...",en,0.000000
3183,wasn't going to go live until monday but gonna...,99,45,731,[],[],en,0.159470
15097,Well we finally have a teeny-weeny bit of high...,92,78,649,[],[btc],en,0.250000
12085,Tether is suspiciously moving around hundreds ...,149,110,637,"[bitcoin, tether]",[btc],en,0.000000
11869,Crypo just following the US stock market right...,40,62,558,[cryptotrash],[btc],en,0.037143

In [187]:
ntwts = df1.tweet[df1.polarity < 0]

In [188]:
ntwts.shape

(2012,)

In [189]:
df1.shape

(12029, 8)

In [190]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [191]:
analyzer = SentimentIntensityAnalyzer()

In [192]:
def getPolarityVader(text):
    return analyzer.polarity_scores(text)

In [193]:
df1['polarityVader'] = df1.tweet.apply(getPolarityVader)

In [194]:
df1.head(10)

,tweet,replies_count,retweets_count,likes_count,hashtags,cashtags,language,polarity,polarityVader
9385,My BTC in long term cold storage will not be t...,187,122,2985,[],[],en,-0.325000,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
8531,The waterfall,212,193,1559,[],[],en,0.000000,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
16138,Sharing some #Bitcoin history Avg correction d...,93,163,875,"[bitcoin, btc]",[],en,0.150000,"{'neg': 0.062, 'neu': 0.809, 'pos': 0.129, 'co..."
13601,Did you buy the dip Drop me the #100xgem of to...,36,865,874,"[100xgem, hodl, btc, eth, solana, bnb, cardano...",[],en,0.000000,"{'neg': 0.1, 'neu': 0.9, 'pos': 0.0, 'compound..."
15763,How are your top #gems doing today Shill me.. ...,43,785,804,"[gems, metaverse, gamefi, bscgem, solanart, nf...",[],en,0.225000,"{'neg': 0.0, 'neu': 0.947, 'pos': 0.053, 'comp..."
11108,"On this day one year ago 1 $BTC $32,957 1 $ETH...",117,189,748,[],"[btc, eth, bnb, sol, ada, luna, avax, matic, c...",en,0.000000,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
3183,wasn't going to go live until monday but gonna...,99,45,731,[],[],en,0.159470,"{'neg': 0.198, 'neu': 0.649, 'pos': 0.152, 'co..."
15097,Well we finally have a teeny-weeny bit of high...,92,78,649,[],[btc],en,0.250000,"{'neg': 0.114, 'neu': 0.814, 'pos': 0.071, 'co..."
12085,Tether is suspiciously moving around hundreds ...,149,110,637,"[bitcoin, tether]",[btc],en,0.000000,"{'neg': 0.119, 'neu': 0.881, 'pos': 0.0, 'comp..."
11869,Crypo just following the US stock market right...,40,62,558,[cryptotrash],[btc],en,0.037143,"{'neg': 0.18, 'neu': 0.699, 'pos': 0.12, 'comp..."

In [195]:
def getCompond(x):
    return x['compound']

In [196]:
df1['polarutyVaderComp'] = df1.polarityVader.apply(getCompond)

In [197]:
df1.head(10)

,tweet,replies_count,retweets_count,likes_count,hashtags,cashtags,language,polarity,polarityVader,polarutyVaderComp
9385,My BTC in long term cold storage will not be t...,187,122,2985,[],[],en,-0.325000,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
8531,The waterfall,212,193,1559,[],[],en,0.000000,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
16138,Sharing some #Bitcoin history Avg correction d...,93,163,875,"[bitcoin, btc]",[],en,0.150000,"{'neg': 0.062, 'neu': 0.809, 'pos': 0.129, 'co...",0.5994
13601,Did you buy the dip Drop me the #100xgem of to...,36,865,874,"[100xgem, hodl, btc, eth, solana, bnb, cardano...",[],en,0.000000,"{'neg': 0.1, 'neu': 0.9, 'pos': 0.0, 'compound...",-0.2732
15763,How are your top #gems doing today Shill me.. ...,43,785,804,"[gems, metaverse, gamefi, bscgem, solanart, nf...",[],en,0.225000,"{'neg': 0.0, 'neu': 0.947, 'pos': 0.053, 'comp...",0.2023
11108,"On this day one year ago 1 $BTC $32,957 1 $ETH...",117,189,748,[],"[btc, eth, bnb, sol, ada, luna, avax, matic, c...",en,0.000000,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
3183,wasn't going to go live until monday but gonna...,99,45,731,[],[],en,0.159470,"{'neg': 0.198, 'neu': 0.649, 'pos': 0.152, 'co...",-0.1212
15097,Well we finally have a teeny-weeny bit of high...,92,78,649,[],[btc],en,0.250000,"{'neg': 0.114, 'neu': 0.814, 'pos': 0.071, 'co...",-0.3111
12085,Tether is suspiciously moving around hundreds ...,149,110,637,"[bitcoin, tether]",[btc],en,0.000000,"{'neg': 0.119, 'neu': 0.881, 'pos': 0.0, 'comp...",-0.4019
11869,Crypo just following the US stock market right...,40,62,558,[cryptotrash],[btc],en,0.037143,"{'neg': 0.18, 'neu': 0.699, 'pos': 0.12, 'comp...",-0.4451

In [198]:
nvtwts = df1.tweet[df1.polarutyVaderComp < 0]

In [199]:
nvtwts.shape #Number of -ve twts

(2674,)

In [200]:
pvtwts = df1.tweet[df1.polarutyVaderComp > 0]

In [201]:
pvtwts.shape #Number of +ve tweets

(5360,)